# Site/SEO settings
email:
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: UA-151888980-1

name: TerminusDB
title: TerminusDB Blog - News and Tutorials
description: >
  News and tutorials of TerminusDB.
url: http://blog.terminusdb.com
twitter_username: TerminusDB
default_img: /assets/images/cowduck_sitting_logo.jpg
social:
  - name: twitter
    url: https://twitter.com/TerminusDB
  - name: github
    url: https://github.com/terminusdb
  - name: Discord
    url: https://discord.gg/Gvdqw97
  - name: youtube
    url: https://www.youtube.com/channel/UC5kZt8pP-FM0u-R0BQr78YA

# Contact settings
contact_img:
formcarry:

# Disqus settings
disqus:

# MailChimp settings
mailchimp_action:
mailchimp_input:

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: 'TerminusDB Blog'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
